### ISSUE TITLE
undefined method `persistent' for #<SomeClass>

### ISSUE THREAD

**Issue by ndyakov** [sportngin/saml_idp#17]
Is there a way to configure what is called on the `principal`?
There is no method in the Configurator that can set those things. I was misled by the snippet in the readme that there should be one.

SomeClass is the class of the principal that I'm passing to `encode_response`

**Comment by jphenow** [comment]
Can you post your configuration code and the stack trace?

**Comment by ndyakov** [comment]
Not until tomorrow, but my configuration was empty because there was no
method to set the name_id_format in the configuration object. I will post
stack trace tomorrow.

**Comment by jphenow** [comment]
Ah I see the confusion now. It appears to no longer be `name_id_format` on the config any more and instead is `name_id.formats` for flexibility. I'll update the readme.

**Comment by jphenow** [comment]
See referencing PR. If I see issues with regards to ongoing compatibility concern here I can write a fix to support the originally doc'd `name_id_formats` entry point

**Comment by ndyakov** [comment]
It is working with `name_id.formats` setting. Thank you!

**Comment by adityaswaroop** [comment]
I am still facing that same issue... what should i pass in encode_response as parameters. What will be the principal class. I passed user object, user email (as stated in spec) but no luck.

Below is my saml request:

<samlp:AuthnRequest AssertionConsumerServiceURL='http://localhost:4000/saml/acs' Destination='http://localhost:4001/saml/auth' ID='_7ac50687-d1a4-444f-82fb-5ab4b163f2f2' IssueInstant='2017-01-12T10:40:04Z' Version='2.0' xmlns:saml='urn:oasis:names:tc:SAML:2.0:assertion' xmlns:samlp='urn:oasis:names:tc:SAML:2.0:protocol'><saml:Issuer>http://localhost:4000/saml/metadata</saml:Issuer><samlp:NameIDPolicy AllowCreate='true' Format='urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress'/><samlp:RequestedAuthnContext Comparison='exact'><saml:AuthnContextClassRef>[&quot;urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport&quot;, &quot;urn:oasis:names:tc:SAML:2.0:ac:classes:Password&quot;]</saml:AuthnContextClassRef></samlp:RequestedAuthnContext></samlp:AuthnRequest>

below is the backtrace:

lib/saml_idp/lib/saml_idp/name_id_formatter.rb:44:in `public_send'
lib/saml_idp/lib/saml_idp/name_id_formatter.rb:44:in `block in build_getter'
lib/saml_idp/lib/saml_idp/assertion_builder.rb:115:in `call'
lib/saml_idp/lib/saml_idp/assertion_builder.rb:115:in `name_id'
lib/saml_idp/lib/saml_idp/assertion_builder.rb:43:in `block (2 levels) in fresh'
lib/saml_idp/lib/saml_idp/assertion_builder.rb:42:in `block in fresh'
lib/saml_idp/lib/saml_idp/assertion_builder.rb:36:in `fresh'
lib/saml_idp/lib/saml_idp/signable.rb:95:in `get_raw'
lib/saml_idp/lib/saml_idp/signable.rb:100:in `noko_raw'
lib/saml_idp/lib/saml_idp/signable.rb:109:in `digest'
lib/saml_idp/lib/saml_idp/signable.rb:84:in `block in get_digest'
lib/saml_idp/lib/saml_idp/signable.rb:56:in `without_signature'
lib/saml_idp/lib/saml_idp/signable.rb:83:in `get_digest'
lib/saml_idp/lib/saml_idp/signable.rb:73:in `signed_info_builder'
lib/saml_idp/lib/saml_idp/signable.rb:68:in `signature'
lib/saml_idp/lib/saml_idp/signable.rb:24:in `sign'
lib/saml_idp/lib/saml_idp/assertion_builder.rb:41:in `block in fresh'
lib/saml_idp/lib/saml_idp/assertion_builder.rb:36:in `fresh'
lib/saml_idp/lib/saml_idp/signable.rb:18:in `block (2 levels) in signed'
lib/saml_idp/lib/saml_idp/signable.rb:47:in `with_signature'
lib/saml_idp/lib/saml_idp/signable.rb:17:in `block in signed'
lib/saml_idp/lib/saml_idp/signable.rb:29:in `generated_reference_id'
lib/saml_idp/lib/saml_idp/signable.rb:16:in `signed'
lib/saml_idp/lib/saml_idp/assertion_builder.rb:82:in `encrypt'
lib/saml_idp/lib/saml_idp/saml_response.rb:53:in `signed_assertion'
lib/saml_idp/lib/saml_idp/saml_response.rb:61:in `response_builder'
lib/saml_idp/lib/saml_idp/saml_response.rb:48:in `build'
lib/saml_idp/lib/saml_idp/controller.rb:55:in `encode_authn_response'
lib/saml_idp/lib/saml_idp/controller.rb:70:in `encode_response'
app/controllers/saml_idp_controller.rb:12:in `idp_make_saml_response'
lib/saml_idp/app/controllers/saml_idp/idp_controller.rb:24:in `create'

Kindly suggest how to resolve this issue
