### ISSUE TITLE
idp_make_saml_response (default NotImplementedError)

### ISSUE THREAD

**Issue by TJM** [sportngin/saml_idp#25]
I wondered why this would not be implemented in idp_controller.rb:

https://github.com/sportngin/saml_idp/blob/master/app/controllers/saml_idp/idp_controller.rb#L37-L39

```
    def idp_make_saml_response(person)
      raise NotImplementedError
    end
```

When it seems fairly simple and straightforward in README.md:

```
  def idp_make_saml_response(found_user) # not using params intentionally
    encode_response found_user
  end
  private :idp_make_saml_response
```

I am sure I must be missing something, but it seems like the code from the README could just be in the class? (although I think I would stick with "person" rather than "found_user") IF the implementation required it to be overridden for whatever reason, they could still do it.

I *do* understand why `idp_authenticate` is setup that way. That is a very implementation specific detail that really wouldn't make sense to have a default method for.

~tommy

**Comment by jphenow** [comment]
That's a fair point, I believe that's a relic of the gem this was forked from which I don't think implemented the encoding method either, making its implementation a bit more required.

I'd be in favor of making that the default behavior.

**Comment by jphenow** [comment]
Leaving this, its intended to be an entry point for the library user to decide how to handle this. Especially given the new encryption options, I'm leaving an opportunity open with which to handle the response and pass options yourself
