### ISSUE TITLE
Adding acs_url for Service Provider in initializer

### ISSUE THREAD

**Issue by ambreenhasan** [sportngin/saml_idp#28]
I've been trying to add the acs_url for the service provider. I currently have the service_providers hash in the initializer like this:

```
service_providers = {
    "localhost:8000/saml" => {
      fingerprint: "9E:65:2E:03:06:8D:80:F2:86:C7:6C:77:A1:D9:14:97:0A:4D:F4:4D",
      metadata_url: "localhost:8000/saml/metadata"
    },
  }
```
But I keep running into an error where acs_url is returning nil even after restarting my rails server. Is this correct or should the url be added elsewhere?

**Comment by ambreenhasan** [comment]
Nevermind, figured this out. :+1:

**Comment by fuadsaud** [comment]
running into the same problem, not sure if I'm missing something

**Comment by jphenow** [comment]
What's the config look like? Is there a stack trace?

**Comment by fuadsaud** [comment]
It was just being set as nil. I've tweaked a couple of things and got it to work, but I believe the problem was that the service provider key in the initialized wasn't matching the issuer url.

**Comment by joeyparis** [comment]
I know it's been a few years @ambreenhasan but how did you figure it out?
