### ISSUE TITLE
metadata_persister is never called

### ISSUE THREAD

**Issue by Yanchek99** [sportngin/saml_idp#33]
The metadata_persister does not seem to be getting hit in any step of my code.  Therefore i have not metadata saved for my SPs.  Is there a configuration step that I am missing?  Struggling to debug this issue, at login I am receiving an "Issuer cannot be verified." error but there is not enough information to debug.

**Comment by jphenow** [comment]
I'm betting that error is why it doesn't hit persister ever. It validates the signature on the metadata document before persisting. That seems like a red-herring though and not like it'd be your actual issue. The persister is more about a between-request memoization and shouldn't actually affect things like this.

I don't see "Issuer cannot be verified" anywhere in the code, so it sounds like the client is disagreeing with the IDP in terms of credentials or signing.

**Comment by Yanchek99** [comment]
@jphenow thank you! Ok so I should look into the certificate exchange and signing. When using a public cert is there a way to null out the secret_key?  `config.secret_key = nil` caused an error when i tried it. Reason I ask is I am trying to get down to bare minimum cert requirements and then build up from there.

**Comment by jphenow** [comment]
Interesting - we should possibly allow that to be nil'd, but you could try an empty string

**Comment by Yanchek99** [comment]
@jphenow I agree that this must be an issue on the SP side of things.  Closing this issue and thank you for the feedback!

**Comment by jphenow** [comment]
Anytime! Good luck :)
