### ISSUE TITLE
Setting config.entity_id does not set issuer in SAML Response

### ISSUE THREAD

**Issue by Yanchek99** [sportngin/saml_idp#34]
Setting the config.entity_id correctly sets the entity id in the metadata response.  However it does not update the issuer in the SAML response, that is defaulted to {host}/saml/auth

Ex. 

`config.entity_id = 'http://localhost:3000`

Metadata Response:

```
<EntityDescriptor xmlns="urn:oasis:names:tc:SAML:2.0:metadata" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" ID="_d6848690-8a51-0133-02e8-14109fe48bcd" entityID="http://localhost:3000">
```

SAML Response:

```
<samlp:Response ID="_cff041b0-8a58-0133-02e9-14109fe48bcd" Version="2.0" IssueInstant="2015-12-21T21:36:26Z" Destination="http://localhost:8080/" Consent="urn:oasis:names:tc:SAML:2.0:consent:unspecified" InResponseTo="_5513e04e119851e5278ffc971f0d03ef5028b930f5" xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"><Issuer xmlns="urn:oasis:names:tc:SAML:2.0:assertion">http://localhost:4000/saml/auth</Issuer>
```

I would assume the entityID in the Metadata Response would equal the Issuer in the SAML Response.

**Comment by arempe93** [comment]
This is a problem for me as well - how can the issuer be set? base_saml_url?

**Comment by jphenow** [comment]
Sorry guys! Trying to get back to helping support this a bit. I no longer work at Sport Ngin, but this was one of the last OSS libs I left so I feel some sense of ownership still. 

Couple different directions here, which maybe points out some oddness in the design at this point (but that's another discussion): 
* You can pass an [`issuer_uri` opt](https://github.com/sportngin/saml_idp/blob/653e9a1ab74f03b289d0714b0bdbb6253e9f4483/lib/saml_idp/controller.rb#L34-L38)
* if that's not passed it looks to the [base-saml](https://github.com/sportngin/saml_idp/blob/653e9a1ab74f03b289d0714b0bdbb6253e9f4483/lib/saml_idp/controller.rb#L79) like you mentioned
* You _could_ probably also just override `def issuer_uri` in your controll that uses the mixin

**Comment by jphenow** [comment]
Open to discussing improvements on the interface there but closing this for now since this stuff is currently possible
