### ISSUE TITLE
Service Provider never gets the sign assertion flag from incoming SP metadata

### ISSUE THREAD

**Issue by Yanchek99** [sportngin/saml_idp#37]
The ServiceProvider object will never get the sign assertions flag from incoming metadata because it is calling from the wrong method signature.  `sign_assertions` vs `sign_assertions`? 

https://github.com/sportngin/saml_idp/blob/master/lib/saml_idp/service_provider.rb#L27
^ Here we can see it checking for a `sign_assertions?` method here `current_metadata.respond_to?(:sign_assertions?) && current_metadata.sign_assertions?`

https://github.com/sportngin/saml_idp/blob/master/lib/saml_idp/incoming_metadata.rb#L19
^ Here we can see that incoming_metadata.rb has no `sign_assertions?` method but instead has a `sign_assertions` method.

**Comment by jphenow** [comment]
Note that current_metadata is a [`PersistedMetadata`](https://github.com/sportngin/saml_idp/blob/master/lib/saml_idp/service_provider.rb#L46) and not an `IncomingMetadata` which does support the `?` method [here](https://github.com/sportngin/saml_idp/blob/master/lib/saml_idp/persisted_metadata.rb#L6)

**Comment by jphenow** [comment]
Is there a bug you were noticing here or were you just looking at code paths and wondered why that was the case?

**Comment by Yanchek99** [comment]
Ah I see, Well I am unable to even really get the metadata from the SP to store in the file.  So I was digging through and modifying some of the code to get it to pull and store the data.  This may have been a result of this thought I don't think I modified much of the code.

**Comment by jphenow** [comment]
Closing for now since it sounds like this was more of a misunderstanding for now. If there are enhancement suggestions or explicit bugs we can discuss and reopen or open new issues as a result.
