### ISSUE TITLE
Document.valid_signature? calls incorrect method to check fingerprint

### ISSUE THREAD

**Issue by Yanchek99** [sportngin/saml_idp#38]
The `valid_signature?` method in the Document class attempts to call a method from xml_security.rb that does not exist. See https://github.com/sportngin/saml_idp/blob/master/lib/saml_idp.rb#L74.

`XMLSecurity::SignedDocument.validate_document(fingerprint, :soft)` is not a supported method for the class.  I believe what it should call is `XMLSecurity::SignedDocument.validate(idp_cert_fingerprint, soft = true)` which can be found here https://github.com/sportngin/saml_idp/blob/master/lib/saml_idp/xml_security.rb#L46

**Comment by jphenow** [comment]
Yea, this looks like a remnant from old code, this seems like a correct assertion.

**Comment by jphenow** [comment]
Also fixed in #41 because awesome
