### ISSUE TITLE
Outdated Readme 

### ISSUE THREAD

**Issue by nqtien310** [sportngin/saml_idp#57]
isn't it supposed to be

```
< SamlIdp::IdpController
```

instead of

```
include SamlIdp::IdpController
```

**Comment by fuzzygroup** [comment]
I've found exactly the same thing.

**Comment by fuzzygroup** [comment]
I've been writing up my progress by creating the wiki:

https://github.com/sportngin/saml_idp/wiki

**Comment by nathanbertram** [comment]
Thanks! I got stuck on this - PR added ^^
